name: oa_fone
description: A new Flutter package project.
version: 1.0.0
homepage: 

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ">=6.0.18 <7.0.0"
  font_awesome_flutter: ">=9.2.0 <10.0.0"
  google_fonts: ">=2.2.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
